# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_query_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.CharField(max_length=30)),
                ('depertment', models.CharField(max_length=30)),
                ('LevelTerm', models.IntegerField()),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
