# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_course_pdf_pdf_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf_table',
            old_name='author',
            new_name='CourseTeacher',
        ),
        migrations.RenameField(
            model_name='pdf_table',
            old_name='lastModified',
            new_name='lastAccessed',
        ),
        migrations.RenameField(
            model_name='pdf_table',
            old_name='uploadeddate',
            new_name='uploadDate',
        ),
    ]
