# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20180111_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_pdf',
            name='Institution',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
