# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_course_pdf_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_table',
            name='vote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
