# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_pdf_table_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleLineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formAttribute', models.CharField(max_length=40)),
            ],
        ),
    ]
