# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_singlelinemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlelinemodel',
            old_name='formAttribute',
            new_name='Field',
        ),
    ]
