# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20180116_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf_table',
            old_name='file',
            new_name='driveID',
        ),
    ]
