# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_uploadfilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
