# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_delete_uploadfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_pdf',
            name='pdfID',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pdf_table',
            name='pdfID',
            field=models.CharField(max_length=40),
        ),
    ]
