# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20180118_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf_table',
            name='lastAccessed',
        ),
    ]
