# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_remove_pdf_table_lastaccessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_table',
            name='lastAccessed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
