# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_uservotetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleLineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=30)),
                ('field2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserTagTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30)),
                ('Tag', models.CharField(max_length=30)),
            ],
        ),
    ]
