# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_doublelinemodel_usertagtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreviewTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30)),
                ('pdfID', models.CharField(max_length=30)),
            ],
        ),
    ]
